# Generated by Django 3.2.3 on 2021-06-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='lead',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='jd',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lead',
            name='next_step',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='rate',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
