# Generated by Django 3.2.3 on 2021-06-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20210607_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
